[General]
VLGDeviceKey=1668648546199|1668756403034|1668990148280|1669082484524|1669169831826
pluginfeaturetag="oldCacheUsing=11.1.0.11664&supportcmdopen=11.1.0.11664&supportroamingpush=11.1.0.11664"
QingIpcVersion=1.0.0.6
SendBy=false
UploadSync=false
crash=1
fileTransfer=false
kicDesktopSyncSwitch=false
kicFileTransferSwitch=false
kicSendBySwitch=false
kicShareFileSwitch=false
kicSyncFolderSwitch=false
kicUploadFileSwitch=false
kicUploadSyncSwitch=false
libpath=/usr/lib/office6/addons/qing
newshare2=false
uploadFile=false
shareFile=false
DesktopSync=false
SpecifyFolderSync=false
specific_companyintro=true
qingVersion=1
RealTimeUploadSwitchFlag=

[activeclient]
7774=1
65953=1
99136=1
34111=1
74285=1
31511=1
287706=1
329634=1
34499=1
19769=1
45221=1
606052=1
125292=1
9253=1
134641=1
299731=1
63016=1
66249=1
921146=1
16651=1
62476=1
242699=1
60383=1
151487=1
48239=1
247923=1
124825=1
216159=1
232012=1
6356=1
340435=1
41897=1
40678=1

[Nse]
IsEnterprise=0

[backup]
DesktopSync=true
SendBy=true
SpecifyFolderSync=true
UploadSync=true
fileTransfer=true
shareFile=true
uploadFile=true

[clouddisk]
batchRemove=1
supportPMoveFolder=1

[msgcenter]
MsgCenterMsgVersion=13

[usercenter]
all\wpsbox\AllDocRadar_Ignore=0
all\wpsbox\MarkShareMsgNewRemind=1
all\wpsbox\Dispersed_AllDocRadar_Ignore=1
all\wpsbox\Radar_Ignore\qqtim=1
all\wpsbox\Radar_Ignore\wechat=1
all\wpsbox\Radar_Ignore\webdownload=1
all\wpsbox\Radar_Ignore\desktop=1
