[services]
lutris = True
gog = True
egs = True
origin = True
ubisoft = True
steam = True

[lutris]
library_ignores = 
migration_version = 12
width = 1226
height = 821
window_x = 630
window_y = 302
maximized = False
selected_category = category:all
filter_installed = False
show_hidden_games = false
show_advanced_options = False
view_type = grid

[list view]
名称_column_width = 200
年份_column_width = 60
运行环境_column_width = 120
平台_column_width = 120
上次游玩_column_width = 120
安装时间_column_width = 120
游玩时间_column_width = 100

