[General]
ApplicationPath=/usr/lib/foxitreader
CurrentSecondToolbar=
ReaderLite_LastPluginUpdateDate=2459714
ReaderLite_LastUpdateDate=2459714
Window%20Position=@Point(1692 -11)
Window%20Size=@Size(1722 1358)
lastOpenFilePath=/home/wano/.deepinwine/Deepin-WeChat/dosdevices/c:/users/wano/My Documents/WeChat Files/wxid_hhtab8bkfu5q22/FileStorage/File/2022-05
recentFileList=/home/wano/.deepinwine/Deepin-WeChat/dosdevices/c:/users/wano/My Documents/WeChat Files/wxid_hhtab8bkfu5q22/FileStorage/File/2022-05/\x4eac\x4e1c\x79d1\x6280-PostgreSQL\x903b\x8f91\x590d\x5236\x89e3\x6790\x30\x35\x31\x34.pdf, "/home/wano/Documents/Books/Data Pipelines with Apache Airflow (Bas P. Harenslak, Julian Rutger de Ruiter) (z-lib.org).pdf"

[Annotation]
Freetext\Format\Align=0
Freetext\Format\BKColor=16777215
Freetext\Format\Bold=0
Freetext\Format\BorderColor=255
Freetext\Format\CharSpace=0.000000
Freetext\Format\CrossOut=0
Freetext\Format\FontName=Helvetica
Freetext\Format\FontSize=9.000
Freetext\Format\HorzScale=100
Freetext\Format\Italic=0
Freetext\Format\LineLeading=0.000000
Freetext\Format\NoBKColor=0
Freetext\Format\ScriptType=0
Freetext\Format\TextColor=16711680
Freetext\Format\UnderLine=0

[GlobalData]
Widget\HighLight=1
Widget\HighLightBar=1
Widget\HighLightColor=16770269
Widget\ReqiredColor=16756912

[HKEY_CURRENT_USER]
SOFTWARE\Foxit%20Software\Foxit%20Reader%201.0\Register\TrialDay=AD6E6601E19BA4A18A1CAFA4C32F5E95

[Preferences]
History\LastOpen\1\Facing=0
History\LastOpen\1\FileName=/home/wano/.deepinwine/Deepin-WeChat/dosdevices/c:/users/wano/My Documents/WeChat Files/wxid_hhtab8bkfu5q22/FileStorage/File/2022-05/\x4eac\x4e1c\x79d1\x6280-PostgreSQL\x903b\x8f91\x590d\x5236\x89e3\x6790\x30\x35\x31\x34.pdf
History\LastOpen\1\Mode=1
History\LastOpen\1\Page=26
History\LastOpen\1\Panels\LeftWidth=305
History\LastOpen\1\Panels\ShowHideAnnotManager\Active=0
History\LastOpen\1\Panels\ShowHideBookmarks\Active=1
History\LastOpen\1\Panels\ShowHideFileAttachment\Active=0
History\LastOpen\1\Panels\ShowHideThumbnails\Active=0
History\LastOpen\1\PosX=0.000000
History\LastOpen\1\PosY=539.999939
History\LastOpen\1\Scale=0.953889
History\LastOpen\1\bShowCoverPage=0
History\LastOpen\1\zoomToMode=4
History\LastOpen\2\Facing=0
History\LastOpen\2\FileName="/home/wano/Documents/Books/Data Pipelines with Apache Airflow (Bas P. Harenslak, Julian Rutger de Ruiter) (z-lib.org).pdf"
History\LastOpen\2\Mode=1
History\LastOpen\2\Page=95
History\LastOpen\2\Panels\LeftWidth=305
History\LastOpen\2\Panels\ShowHideAnnotManager\Active=0
History\LastOpen\2\Panels\ShowHideBookmarks\Active=1
History\LastOpen\2\Panels\ShowHideFileAttachment\Active=0
History\LastOpen\2\Panels\ShowHideThumbnails\Active=0
History\LastOpen\2\PosX=0.000000
History\LastOpen\2\PosY=510.976257
History\LastOpen\2\Scale=1.726027
History\LastOpen\2\bShowCoverPage=0
History\LastOpen\2\zoomToMode=4
Others\bCheckExpireDate=0
Others\bCheckRegister=0
Others\bCheckStandardFeature=1
Others\bCheckStandardLimited=1
Others\bCheckStandardSave=1
Others\bDisableSharePointFeatures=0
Others\bEnableJS=1
Others\bSeparateMenubar=1
Others\bShowAD=1
Others\bShowOpenURLMessageBox=0
Others\bShowTraileDlg=1
Others\bShowWelcomeDlg=0
Others\bShowXFAWarn=1
Others\csFileSavePLGEXT=
Others\csInitialOpenDir=
Others\nAdvertiseId=0
Others\nFileSaveType=0
Others\nPreferItem=

[Register]
FPMStatus=Express

[SnapShot]
CheckSnapShot=1
