[Patch]

[Setting]
prefs_path              = /home/wano/.config/spotify/prefs
current_theme           = SpicetifyDefault
inject_css              = 1
replace_colors          = 1
spotify_path            = /opt/spotify
color_scheme            = nord-light
overwrite_assets        = 0
spotify_launch_flags    = 
check_spicetify_upgrade = 0

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
home_config           = 1
experimental_features = 1
extensions            = 
custom_apps           = 
sidebar_config        = 1

; DO NOT CHANGE!
[Backup]
version = 1.1.84.716.gc5f8b819
with    = Dev

